### ISSUE TITLE
orthography profile needs improvement

### ISSUE THREAD

**Issue by LinguList** [lexibank/hubercolumbian#1]
there are many errors or inconsistencies. Can be ignored for time being, but definitely something that needs to be addressed int eh future!

**Comment by SimonGreenhill** [comment]
can you remember what the issues were here?

**Comment by tresoldi** [comment]
Can't see much other than some diacritics being dropped. The tones are also stripped, as in most cases, but it is not a real issue.

**Comment by SimonGreenhill** [comment]
ok, reopen if it's something more problematic.
