### ISSUE TITLE
Missing sources.bib

### ISSUE THREAD

**Issue by chrzyki** [lexibank/hubercolumbian#3]
https://github.com/lexibank/hubercolumbian/commit/c7a231ece4f50e174137c6be3c3761d851d3e88c#diff-9a7494ac6e551ac5c0f4687b20142c0dR54

@SimonGreenhill do you maybe have an uncommitted `sources.bib` somewhere?

**Comment by SimonGreenhill** [comment]
Yes! sorry -- just pushed.

**Comment by chrzyki** [comment]
Thanks!
