### ISSUE TITLE
Updated to new pylexibank

### ISSUE THREAD

**Issue by chrzyki** [lexibank/hubercolumbian#4]
Here: https://github.com/lexibank/hubercolumbian/commit/4649f52a395618e212207eb0902ebb156ffe0e43

In terms of pylexibank 2.0 compatibility not much needed to be done. But we still want the other potential refactorings here, I think?

- concept mapping & concept ids
- language mapping (maybe? circumventing the `wl._meta` construct?)
- anything else?

**Comment by SimonGreenhill** [comment]
Yeah, I think avoiding wl._meta is worth avoiding if we can for simplicity's sake. However, if it isn't broke, don't fix it.

One minor request, can you get rid of tqdm and replace with pylexibank.util.pb? danke!

**Comment by chrzyki** [comment]
Ah, sorry! Fixed.

**Comment by LinguList** [comment]
I left a few comments. I'd say: ideally, just add `etc/languages.csv`, with coordinates, if possible, and good ids (no lower-case-slugging). And for the concepticon-concepts, I'd prefer normal IDs, folllowing our style. The ones we have now caused a lot of damage in the past (as they were taken as representing the concepts themselves)...

**Comment by chrzyki** [comment]
Just updated with the new concept list, please see here: https://github.com/lexibank/hubercolumbian/commit/2e1dc928230b20d441ed9189e045721f4defcc69

Please have a look at this:

https://github.com/lexibank/hubercolumbian/blob/2e1dc928230b20d441ed9189e045721f4defcc69/lexibank_hubercolumbian.py#L78-L80

Of course I want to remove this. The original ('wrong') concept list didn't distinguish between the two `we`'s, the original source, however, does. The lexeme list, however, does not (as far as I can tell). How do we deal with this?

Likewise, the original concept list had `it` as a concept, the source doesn't have that. Do I manually provide these mappings?

Tomorrow I'll take care of the languages that @LinguList mentioned.

**Comment by LinguList** [comment]
the problem is the data itself, and I think, we have to REMAP the conceptlist in Huber, so we should not release concepticon before this is done (sorry, @xrotwang ...).

**Comment by LinguList** [comment]
the huber source itself is ambiguous. They list we (exclusive) and we (inclusive) in their concept list, which you typed off now, but they do NOT list them separately on page 199, under item 205, where you actually need to look. The number 205 is the header of the concept list, and this page listts various forms for different languages, but idt does not really give usa n indication which "we" we talk about here. Some languages clearly seem to have the distinction, others not. So the best way to go with this is to say: Huber does onnly have WE, not we (exclusive) vs. we (inclusive).

**Comment by LinguList** [comment]
I am afraid, the only thing that can be done now is to go through the actual wordlist in huber, and check if the Numbers (the ones on top in the PDF) are actually correct. Right now, they aren't: we miss "ello / it", but we have it in the book. The digital data we have is reflecting the book, not the last page of the book. So what should be done is:

1. refine huber again, but this time (and many things are already correct here, so not that much work) the numbers per page in huber and reed (you have the PDF, right?)
2. base the concept list on that list ONLY
3. update the list on concepticon, mention in the note that the index in the book has problems
4. update pylexibank.

**Comment by LinguList** [comment]
sorry for this, but I thought that you had already checked the concepts in the book, I mean, the entries, where the languages are. Otherwise, I would have warned you that this is the thing that the concept list should be based on. Although I have to say: I would not have expected that the actual pages would be differentt from the index...

**Comment by LinguList** [comment]
[huber-1992.tsv.zip](https://github.com/lexibank/hubercolumbian/files/3809953/huber-1992.tsv.zip)

**Comment by LinguList** [comment]
This is the first 101 concepts, typed off, following the book. I type rather fast, so it did not take me too long. One could also compare, as the order is more or less the same, but I would say: reduce concepticon to exactly those numbers there, this should be our standard list of concepts for huber, as it is the source that gives us the language data.

**Comment by LinguList** [comment]
And this source has exactly 375 numbers as concepts, so 375 pages with words for actual languages.

**Comment by xrotwang** [comment]
What exactly does that entail? The concept list is now correct, I.e.
follows the source, right? So the raw data must be re-assessed?

Johann-Mattis List <notifications@github.com> schrieb am Di., 5. Nov. 2019,
17:17:

**Comment by chrzyki** [comment]
Well, that is on me then, apologies. We were working on the basis of this:

https://cdstar.shh.mpg.de/bitstreams/EAEA0-78F1-75A6-501A-0/Huber1992.pdf

**Comment by chrzyki** [comment]
> 
> 
> sorry for this, but I thought that you had already checked the concepts in the book, I mean, the entries, where the languages are. Otherwise, I would have warned you that this is the thing that the concept list should be based on. Although I have to say: I would not have expected that the actual pages would be differentt from the index...

No worries, I should have been more careful here. Sorry for this messy situation. Will attempt to fix this first thing in the morning.

**Comment by LinguList** [comment]
> What exactly does that entail? The concept list is now correct, I.e.
follows the source, right? So the raw data must be re-assessed?

No, the concept list does follow the page of contens in the source, but not the actual source. The page of contents is wrong in the source, with concepts falsely assigned, and concepts missing. The source in digital form we have is in this sense correct, what is wrong is to only type of the table of contents with the concepts in list form and not look at the pages with the actual language entries.

**Comment by LinguList** [comment]
Okay, with the last PR, we still need somebody to check the issues mentioned by @tresoldi, and I corrected some concepticon mappings as well. But otherwise, we are, I hope, good to go, once this is solved, so can release concepticon 2.2. tomorrow by lunch time, I hope.

**Comment by chrzyki** [comment]
Done
