### ISSUE TITLE
'etc' in raw data & output

### ISSUE THREAD

**Issue by chrzyki** [lexibank/hubercolumbian#9]
There are three instances of the string 'etc' as value/form in the raw data and in the output:

- Guahibo-145_termite-2
- Guahibo-329_cut-4
- Koreguaje-146_ant-3

Are these artifacts?

**Comment by xrotwang** [comment]
Or hard to pronounce words :)

**Comment by chrzyki** [comment]
Looks like it, but I still wanted to check just in case. :) Looking forward to finding a `cat /etc/passwd` form/value somewhere.

**Comment by xrotwang** [comment]
That would be cool. Long range hack by Huber from 1992!

**Comment by LinguList** [comment]
Let us try to extinguish all etcs! Do you have the original to check, @chrzyki ?

**Comment by chrzyki** [comment]
First and third case I've found in the source material, I can't find data for the second case, however:

![etc1](https://user-images.githubusercontent.com/4689035/115014895-35919500-9eb3-11eb-8aff-8e3857cfcfa5.png)

![etc3](https://user-images.githubusercontent.com/4689035/115014902-37f3ef00-9eb3-11eb-88a3-e3c3d041d71a.png)

**Comment by LinguList** [comment]
Okay, so deleting etc., taht is, putting it our list of "exclude" is 
then very important!

**Comment by chrzyki** [comment]
Okay, thanks for checking, I'll do that.
